[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/orders/*"
  to = "/.netlify/functions/orders/:splat"
  status = 200

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/api/bookings/*"
  to = "/.netlify/functions/bookings/:splat"
  status = 200

[[redirects]]
  from = "/api/bookings"
  to = "/.netlify/functions/bookings"
  status = 200

[[redirects]]
  from = "/api/users/*"
  to = "/.netlify/functions/users/:splat"
  status = 200

[[redirects]]
  from = "/api/users"
  to = "/.netlify/functions/users"
  status = 200
